from .card import Card
from .. import suits


class Cards:
    spade_king = Card(suits.SPADE, 13)
    spade_queen = Card(suits.SPADE, 12)
    spade_jack = Card(suits.SPADE, 11)
    spade_10 = Card(suits.SPADE, 10)
    spade_9 = Card(suits.SPADE, 9)
    spade_8 = Card(suits.SPADE, 8)
    spade_7 = Card(suits.SPADE, 7)
    spade_6 = Card(suits.SPADE, 6)
    spade_5 = Card(suits.SPADE, 5)
    spade_4 = Card(suits.SPADE, 4)
    spade_3 = Card(suits.SPADE, 3)
    spade_2 = Card(suits.SPADE, 2)
    spade_ace = Card(suits.SPADE, 1)

    heart_king = Card(suits.HEART, 13)
    heart_queen = Card(suits.HEART, 12)
    heart_jack = Card(suits.HEART, 11)
    heart_10 = Card(suits.HEART, 10)
    heart_9 = Card(suits.HEART, 9)
    heart_8 = Card(suits.HEART, 8)
    heart_7 = Card(suits.HEART, 7)
    heart_6 = Card(suits.HEART, 6)
    heart_5 = Card(suits.HEART, 5)
    heart_4 = Card(suits.HEART, 4)
    heart_3 = Card(suits.HEART, 3)
    heart_2 = Card(suits.HEART, 2)
    heart_ace = Card(suits.HEART, 1)

    diamond_king = Card(suits.DIAMOND, 13)
    diamond_queen = Card(suits.DIAMOND, 12)
    diamond_jack = Card(suits.DIAMOND, 11)
    diamond_10 = Card(suits.DIAMOND, 10)
    diamond_9 = Card(suits.DIAMOND, 9)
    diamond_8 = Card(suits.DIAMOND, 8)
    diamond_7 = Card(suits.DIAMOND, 7)
    diamond_6 = Card(suits.DIAMOND, 6)
    diamond_5 = Card(suits.DIAMOND, 5)
    diamond_4 = Card(suits.DIAMOND, 4)
    diamond_3 = Card(suits.DIAMOND, 3)
    diamond_2 = Card(suits.DIAMOND, 2)
    diamond_ace = Card(suits.DIAMOND, 1)

    club_king = Card(suits.CLUB, 13)
    club_queen = Card(suits.CLUB, 12)
    club_jack = Card(suits.CLUB, 11)
    club_10 = Card(suits.CLUB, 10)
    club_9 = Card(suits.CLUB, 9)
    club_8 = Card(suits.CLUB, 8)
    club_7 = Card(suits.CLUB, 7)
    club_6 = Card(suits.CLUB, 6)
    club_5 = Card(suits.CLUB, 5)
    club_4 = Card(suits.CLUB, 4)
    club_3 = Card(suits.CLUB, 3)
    club_2 = Card(suits.CLUB, 2)
    club_ace = Card(suits.CLUB, 1)
