from .card import Card


class Cards:
    SPADE = 'Spade'
    spade_king = Card(SPADE, 13)
    spade_queen = Card(SPADE, 12)
    spade_jack = Card(SPADE, 11)
    spade_10 = Card(SPADE, 10)
    spade_9 = Card(SPADE, 9)
    spade_8 = Card(SPADE, 8)
    spade_7 = Card(SPADE, 7)
    spade_6 = Card(SPADE, 6)
    spade_5 = Card(SPADE, 5)
    spade_4 = Card(SPADE, 4)
    spade_3 = Card(SPADE, 3)
    spade_2 = Card(SPADE, 2)
    spade_ace = Card(SPADE, 1)

    HEART = 'Heart'
    heart_king = Card(HEART, 13)
    heart_queen = Card(HEART, 12)
    heart_jack = Card(HEART, 11)
    heart_10 = Card(HEART, 10)
    heart_9 = Card(HEART, 9)
    heart_8 = Card(HEART, 8)
    heart_7 = Card(HEART, 7)
    heart_6 = Card(HEART, 6)
    heart_5 = Card(HEART, 5)
    heart_4 = Card(HEART, 4)
    heart_3 = Card(HEART, 3)
    heart_2 = Card(HEART, 2)
    heart_ace = Card(HEART, 1)

    DIAMOND = 'Diamond'
    diamond_king = Card(DIAMOND, 13)
    diamond_queen = Card(DIAMOND, 12)
    diamond_jack = Card(DIAMOND, 11)
    diamond_10 = Card(DIAMOND, 10)
    diamond_9 = Card(DIAMOND, 9)
    diamond_8 = Card(DIAMOND, 8)
    diamond_7 = Card(DIAMOND, 7)
    diamond_6 = Card(DIAMOND, 6)
    diamond_5 = Card(DIAMOND, 5)
    diamond_4 = Card(DIAMOND, 4)
    diamond_3 = Card(DIAMOND, 3)
    diamond_2 = Card(DIAMOND, 2)
    diamond_ace = Card(DIAMOND, 1)

    CLUB = 'Club'
    club_king = Card(CLUB, 13)
    club_queen = Card(CLUB, 12)
    club_jack = Card(CLUB, 11)
    club_10 = Card(CLUB, 10)
    club_9 = Card(CLUB, 9)
    club_8 = Card(CLUB, 8)
    club_7 = Card(CLUB, 7)
    club_6 = Card(CLUB, 6)
    club_5 = Card(CLUB, 5)
    club_4 = Card(CLUB, 4)
    club_3 = Card(CLUB, 3)
    club_2 = Card(CLUB, 2)
    club_ace = Card(CLUB, 1)
